/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.ui.common.helper.CountryUIHelper;
import dpu.Validations;
import dpu.beans.admin.CountryBean;
import dpu.beans.admin.CountryBean;
import dpu.dao.admin.CountryDAO;
import dpu.dao.admin.impl.CountryDAOImpl;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class AddCountryFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddCountry
     */
    String msg = "";
    CountryUIHelper countryUI = null;
    String addUpdateFlag = "";
    CountryBean countryBean;

    public AddCountryFrame() {
        initComponents();
        setIconImage(new ImageIcon("src\\dpu\\ui\\common\\Application-Icon.png").getImage());
        setLocationRelativeTo(null);
        countryUI = new CountryUIHelper();
        btnSaveAddCountry.setEnabled(false);
        fillLabel();
    }

    public AddCountryFrame(CountryBean countryBean) {
        initComponents();
        setIconImage(new ImageIcon("src\\dpu\\ui\\common\\Application-Icon.png").getImage());
        countryUI = new CountryUIHelper();
        this.countryBean = countryBean;
        setLocationRelativeTo(null);
        addUpdateFlag = "update";
        showRecord(countryBean);
        btnSaveAddCountry.setText("Update");
        btnSaveAddCountry.setEnabled(true);
    }
    
    private void fillLabel() {
        lblCountryIdAddCountryFrameValidation.setText(" ");
        lblCountryNameAddCountryFrameValidation.setText(" ");
    }

    public boolean validateCountryId(String str) {
        if (Validations.isEmpty(str)) {
            msg = "Left Empty..!";
            return false;
        }
        if (Validations.hasNumerals(str)) {
            msg = "Only Numerics Allowed..!";
            return false;
        }
        if (Validations.hasSpace(str)) {
            msg = "Space Not Allowed..!";
            return false;
        }
        return true;
    }

    public boolean validateCountryName(String str) {
        if (Validations.isEmpty(str)) {
            msg = "Left Empty..!";
            return false;
        }
        if (Validations.hasAlphabets(str)) {
            msg = "Only Alphabets Allowed..!";
            return false;
        }
        if (Validations.hasSpace(str)) {
            msg = "Space Not Allowed..!";
            return false;
        }
        return true;
    }

    public void showRecord(CountryBean countryBean) {
        txtCountryIdAddCountry.setText(String.valueOf(countryBean.getCountryId()));
        txtCountryNameAddCountry.setText(countryBean.getCountryName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCountryIdAddCountry = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCountryNameAddCountry = new javax.swing.JTextField();
        btnSaveAddCountry = new javax.swing.JButton();
        btnCancelAddCountry = new javax.swing.JButton();
        lblCountryIdAddCountryFrameValidation = new javax.swing.JLabel();
        lblCountryNameAddCountryFrameValidation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Company Id");

        txtCountryIdAddCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryIdAddCountryActionPerformed(evt);
            }
        });
        txtCountryIdAddCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCountryIdAddCountryKeyReleased(evt);
            }
        });

        jLabel8.setText("Company Name");

        txtCountryNameAddCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryNameAddCountryActionPerformed(evt);
            }
        });
        txtCountryNameAddCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCountryNameAddCountryKeyReleased(evt);
            }
        });

        btnSaveAddCountry.setText("Save");
        btnSaveAddCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddCountryActionPerformed(evt);
            }
        });

        btnCancelAddCountry.setText("Cancel");
        btnCancelAddCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddCountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveAddCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelAddCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCountryNameAddCountry)
                            .addComponent(txtCountryIdAddCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCountryIdAddCountryFrameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCountryNameAddCountryFrameValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelAddCountry, btnSaveAddCountry});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCountryIdAddCountryFrameValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCountryIdAddCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtCountryNameAddCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountryNameAddCountryFrameValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveAddCountry)
                    .addComponent(btnCancelAddCountry))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCountryIdAddCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryIdAddCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryIdAddCountryActionPerformed

    private void btnCancelAddCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddCountryActionPerformed
        dispose();
        countryUI.disable(true);
    }//GEN-LAST:event_btnCancelAddCountryActionPerformed

    private void btnSaveAddCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddCountryActionPerformed
        String msg = "";
        if (addUpdateFlag.equals("update")) {
            countryBean = new CountryBean();
            countryBean.setCountryId(Integer.parseInt(txtCountryIdAddCountry.getText()));
            countryBean.setCountryName(txtCountryNameAddCountry.getText());
            msg = countryUI.update(countryBean);
        } else {
            msg = countryUI.save();
        }
        JOptionPane.showMessageDialog(null, msg);
        dispose();
    }//GEN-LAST:event_btnSaveAddCountryActionPerformed

    private void txtCountryIdAddCountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCountryIdAddCountryKeyReleased
        CountryDAO countryDAO = new CountryDAOImpl();
        List<CountryBean> lstCompanies = countryDAO.getAllCountries("");
        try {
            if (validateCountryId(txtCountryIdAddCountry.getText())) {
                lblCountryIdAddCountryFrameValidation.setText("");
                for (CountryBean countryBean : lstCompanies) {
                    if (countryBean.getCountryId() == Integer.parseInt(txtCountryIdAddCountry.getText().trim())) {
                        lblCountryIdAddCountryFrameValidation.setText("Already Taken");
                        btnSaveAddCountry.setEnabled(false);
                    }
                }
            } else {
                lblCountryIdAddCountryFrameValidation.setText(msg);
                btnSaveAddCountry.setEnabled(false);
            }
            if (lblCountryIdAddCountryFrameValidation.getText().equals("") && lblCountryNameAddCountryFrameValidation.getText().equals("")) {
                btnSaveAddCountry.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtCountryIdAddCountryKeyReleased

    private void txtCountryNameAddCountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCountryNameAddCountryKeyReleased
        CountryDAO countryDAO = new CountryDAOImpl();
        List<CountryBean> lstCountries = countryDAO.getAllCountries("");
        try {
            if (validateCountryName(txtCountryNameAddCountry.getText())) {
                lblCountryNameAddCountryFrameValidation.setText("");
                for (CountryBean countryBean : lstCountries) {
                    if (countryBean.getCountryName().equals(txtCountryNameAddCountry.getText().trim())) {
                        lblCountryNameAddCountryFrameValidation.setText("Already Taken");
                        btnSaveAddCountry.setEnabled(false);
                    }
                }
            } else {
                lblCountryNameAddCountryFrameValidation.setText(msg);
                btnSaveAddCountry.setEnabled(false);
            }
            if (lblCountryIdAddCountryFrameValidation.getText().equals("") && lblCountryNameAddCountryFrameValidation.getText().equals("")) {
                btnSaveAddCountry.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtCountryNameAddCountryKeyReleased

    private void txtCountryNameAddCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryNameAddCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryNameAddCountryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCountryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCountryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCountryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCountryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCountryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelAddCountry;
    private javax.swing.JButton btnSaveAddCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCountryIdAddCountryFrameValidation;
    private javax.swing.JLabel lblCountryNameAddCountryFrameValidation;
    public static javax.swing.JTextField txtCountryIdAddCountry;
    public static javax.swing.JTextField txtCountryNameAddCountry;
    // End of variables declaration//GEN-END:variables
}
