/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.ui.common.helper.CompanyUIHelper;
import dpu.Validations;
import dpu.beans.admin.CompanyBean;
import dpu.beans.admin.CompanyBean;
import dpu.dao.admin.CompanyDAO;
import dpu.dao.admin.impl.CompanyDAOImpl;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class AddCompanyFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddCompany
     */
    String msg = "";
    CompanyUIHelper companyUI = null;
    String addUpdateFlag = "";
    CompanyBean companyBean;

    public AddCompanyFrame() {
        initComponents();
        setIconImage(new ImageIcon("src\\dpu\\ui\\common\\Application-Icon.png").getImage());
        setLocationRelativeTo(null);
        companyUI = new CompanyUIHelper();
        btnSaveAddCompany.setEnabled(false);
    }

    public AddCompanyFrame(CompanyBean companyBean) {
        initComponents();
        companyUI = new CompanyUIHelper();
        this.companyBean = companyBean;
        setLocationRelativeTo(null);
        addUpdateFlag = "update";
        showRecord(companyBean);
        btnSaveAddCompany.setText("Update");
        btnSaveAddCompany.setEnabled(true);
    }

    public boolean validateCompanyId(String str) {
        if (Validations.isEmpty(str)) {
            msg = "Left Empty..!";
            return false;
        }
        if (Validations.hasNumerals(str)) {
            msg = "Only Numerics Allowed..!";
            return false;
        }
        if (Validations.hasSpace(str)) {
            msg = "Space Not Allowed..!";
            return false;
        }
        return true;
    }

    public boolean validateCompanyName(String str) {
        if (Validations.isEmpty(str)) {
            msg = "Left Empty..!";
            return false;
        }
        if (Validations.hasAlphabets(str)) {
            msg = "Only Alphabets Allowed..!";
            return false;
        }
        if (Validations.hasSpace(str)) {
            msg = "Space Not Allowed..!";
            return false;
        }
        return true;
    }

    public void showRecord(CompanyBean companyBean) {
        txtCompanyIdAddCompany.setText(String.valueOf(companyBean.getCompanyId()));
        txtCompanyNameAddCompany.setText(companyBean.getCompanyName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCompanyIdAddCompany = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCompanyNameAddCompany = new javax.swing.JTextField();
        btnSaveAddCompany = new javax.swing.JButton();
        btnCancelAddCompany = new javax.swing.JButton();
        lblCompanyIdAddCompanyFrameValidation = new javax.swing.JLabel();
        lblCompanyNameAddCompanyFrameValidation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Company Id");

        txtCompanyIdAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyIdAddCompanyActionPerformed(evt);
            }
        });
        txtCompanyIdAddCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompanyIdAddCompanyKeyReleased(evt);
            }
        });

        jLabel8.setText("Company Name");

        txtCompanyNameAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameAddCompanyActionPerformed(evt);
            }
        });
        txtCompanyNameAddCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompanyNameAddCompanyKeyReleased(evt);
            }
        });

        btnSaveAddCompany.setText("Save");
        btnSaveAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddCompanyActionPerformed(evt);
            }
        });

        btnCancelAddCompany.setText("Cancel");
        btnCancelAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddCompanyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveAddCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelAddCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCompanyNameAddCompany)
                            .addComponent(txtCompanyIdAddCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCompanyIdAddCompanyFrameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCompanyNameAddCompanyFrameValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelAddCompany, btnSaveAddCompany});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompanyIdAddCompanyFrameValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCompanyIdAddCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtCompanyNameAddCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompanyNameAddCompanyFrameValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveAddCompany)
                    .addComponent(btnCancelAddCompany))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompanyIdAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyIdAddCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyIdAddCompanyActionPerformed

    private void btnCancelAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddCompanyActionPerformed
        dispose();
        companyUI.disable(true);
    }//GEN-LAST:event_btnCancelAddCompanyActionPerformed

    private void btnSaveAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddCompanyActionPerformed
        String msg = "";
        if (addUpdateFlag.equals("update")) {
            companyBean = new CompanyBean();
            companyBean.setCompanyId(Integer.parseInt(txtCompanyIdAddCompany.getText()));
            companyBean.setCompanyName(txtCompanyNameAddCompany.getText());
            msg = companyUI.update(companyBean);
        } else {
            msg = companyUI.save();
        }
        JOptionPane.showMessageDialog(null, msg);
        dispose();
    }//GEN-LAST:event_btnSaveAddCompanyActionPerformed

    private void txtCompanyIdAddCompanyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompanyIdAddCompanyKeyReleased
        CompanyDAO companyDAO = new CompanyDAOImpl();
        List<CompanyBean> lstCompanies = companyDAO.getAllCompanies("");
        try {
            if (validateCompanyId(txtCompanyIdAddCompany.getText())) {
                lblCompanyIdAddCompanyFrameValidation.setText("");
                for (CompanyBean companyBean : lstCompanies) {
                    if (companyBean.getCompanyId() == Integer.parseInt(txtCompanyIdAddCompany.getText().trim())) {
                        lblCompanyIdAddCompanyFrameValidation.setText("Already Taken");
                        btnSaveAddCompany.setEnabled(false);
                    }
                }
            } else {
                lblCompanyIdAddCompanyFrameValidation.setText(msg);
                btnSaveAddCompany.setEnabled(false);
            }
            if (lblCompanyIdAddCompanyFrameValidation.getText().equals("") && lblCompanyNameAddCompanyFrameValidation.getText().equals("")) {
                btnSaveAddCompany.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtCompanyIdAddCompanyKeyReleased

    private void txtCompanyNameAddCompanyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompanyNameAddCompanyKeyReleased
        CompanyDAO companyDAO = new CompanyDAOImpl();
        List<CompanyBean> lstCompanies = companyDAO.getAllCompanies("");
        try {
            if (validateCompanyName(txtCompanyNameAddCompany.getText())) {
                lblCompanyNameAddCompanyFrameValidation.setText("");
                for (CompanyBean companyBean : lstCompanies) {
                    if (companyBean.getCompanyName().equals(txtCompanyNameAddCompany.getText().trim())) {
                        lblCompanyNameAddCompanyFrameValidation.setText("Already Taken");
                        btnSaveAddCompany.setEnabled(false);
                    }
                }
            } else {
                lblCompanyNameAddCompanyFrameValidation.setText(msg);
                btnSaveAddCompany.setEnabled(false);
            }
            if (lblCompanyIdAddCompanyFrameValidation.getText().equals("") && lblCompanyNameAddCompanyFrameValidation.getText().equals("")) {
                btnSaveAddCompany.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtCompanyNameAddCompanyKeyReleased

    private void txtCompanyNameAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameAddCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameAddCompanyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCompanyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelAddCompany;
    private javax.swing.JButton btnSaveAddCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCompanyIdAddCompanyFrameValidation;
    private javax.swing.JLabel lblCompanyNameAddCompanyFrameValidation;
    public static javax.swing.JTextField txtCompanyIdAddCompany;
    public static javax.swing.JTextField txtCompanyNameAddCompany;
    // End of variables declaration//GEN-END:variables
}
