/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.ui.helper.common.DivisionUIHelper;
import dpu.Validations;
import dpu.beans.admin.DivisionBean;
import dpu.dao.admin.DivisionDAO;
import dpu.dao.admin.impl.DivisionDAOImpl;
import java.util.List;
import javax.swing.JOptionPane;

public class AddDivisionFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddDivision
     */

    String msg = "";
    DivisionUIHelper divisionUI = null;
    String addUpdateFlag = "";
    DivisionBean divisionBean;

    public AddDivisionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        divisionUI = new DivisionUIHelper();
        btnSaveAddDivision.setEnabled(false);
    }

    public AddDivisionFrame(DivisionBean divisionBean) {
        initComponents();
        divisionUI = new DivisionUIHelper();
        this.divisionBean = divisionBean;
        setLocationRelativeTo(null);
        addUpdateFlag = "update";
        showRecord(divisionBean);
        btnSaveAddDivision.setText("Update");
        btnSaveAddDivision.setEnabled(true);
    }

    public boolean validateDivisionId(String str) {
        if (Validations.isEmpty(str)) {
            msg = "Left Empty..!";
            return false;
        }
        if (Validations.hasNumerals(str)) {
            msg = "Only Numerics Allowed..!";
            return false;
        }
        if (Validations.hasSpace(str)) {
            msg = "Space Not Allowed..!";
            return false;
        }
        return true;
    }

    public boolean validateDivisionName(String str) {
        if (Validations.isEmpty(str)) {
            msg = "Left Empty..!";
            return false;
        }
        if (Validations.hasAlphabets(str)) {
            msg = "Only Alphabets Allowed..!";
            return false;
        }
        if (Validations.hasSpace(str)) {
            msg = "Space Not Allowed..!";
            return false;
        }
        return true;
    }

    public void showRecord(DivisionBean divisionBean) {
        txtDivisionIdAddDivision.setText(String.valueOf(divisionBean.getDivisionId()));
        txtDivisionNameAddDivision.setText(divisionBean.getDivision());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDivisionIdAddDivision = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDivisionNameAddDivision = new javax.swing.JTextField();
        btnSaveAddDivision = new javax.swing.JButton();
        btnCancelAddDivision = new javax.swing.JButton();
        lblDivisionIdAddDivisionFrameValidation = new javax.swing.JLabel();
        lblDivisionNameAddDivisionFrameValidation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Division Id");

        txtDivisionIdAddDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDivisionIdAddDivisionActionPerformed(evt);
            }
        });
        txtDivisionIdAddDivision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDivisionIdAddDivisionKeyReleased(evt);
            }
        });

        jLabel8.setText("Division Name");

        txtDivisionNameAddDivision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDivisionNameAddDivisionKeyReleased(evt);
            }
        });

        btnSaveAddDivision.setText("Save");
        btnSaveAddDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddDivisionActionPerformed(evt);
            }
        });

        btnCancelAddDivision.setText("Cancel");
        btnCancelAddDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddDivisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveAddDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelAddDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDivisionNameAddDivision)
                            .addComponent(txtDivisionIdAddDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDivisionIdAddDivisionFrameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDivisionNameAddDivisionFrameValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelAddDivision, btnSaveAddDivision});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDivisionIdAddDivisionFrameValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtDivisionIdAddDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtDivisionNameAddDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDivisionNameAddDivisionFrameValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveAddDivision)
                    .addComponent(btnCancelAddDivision))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDivisionIdAddDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDivisionIdAddDivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDivisionIdAddDivisionActionPerformed

    private void btnCancelAddDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddDivisionActionPerformed
        dispose();
        divisionUI.disable(true);
    }//GEN-LAST:event_btnCancelAddDivisionActionPerformed

    private void btnSaveAddDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddDivisionActionPerformed
        String msg = "";
        if (addUpdateFlag.equals("update")) {
            divisionBean = new DivisionBean();
            divisionBean.setDivisionId(Integer.parseInt(txtDivisionIdAddDivision.getText()));
            divisionBean.setDivision(txtDivisionNameAddDivision.getText());
            msg = divisionUI.update(divisionBean);
        } else {
            msg = divisionUI.save();
        }
        JOptionPane.showMessageDialog(null, msg);
        dispose();
    }//GEN-LAST:event_btnSaveAddDivisionActionPerformed

    private void txtDivisionIdAddDivisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDivisionIdAddDivisionKeyReleased
        DivisionDAO divisionDAO = new DivisionDAOImpl();
        List<DivisionBean> lstDivisions = divisionDAO.getAllDivisions("");
        try {
            if (validateDivisionId(txtDivisionIdAddDivision.getText())) {
                lblDivisionIdAddDivisionFrameValidation.setText("");
                for (DivisionBean divisionBean : lstDivisions) {
                    if (divisionBean.getDivisionId() == Integer.parseInt(txtDivisionIdAddDivision.getText().trim())) {
                        lblDivisionIdAddDivisionFrameValidation.setText("Already Taken");
                        btnSaveAddDivision.setEnabled(false);
                    }
                }
            } else {
                lblDivisionIdAddDivisionFrameValidation.setText(msg);
                btnSaveAddDivision.setEnabled(false);
            }
            if (lblDivisionIdAddDivisionFrameValidation.getText().equals("") && lblDivisionNameAddDivisionFrameValidation.getText().equals("")) {
                btnSaveAddDivision.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtDivisionIdAddDivisionKeyReleased

    private void txtDivisionNameAddDivisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDivisionNameAddDivisionKeyReleased
        DivisionDAO divisionDAO = new DivisionDAOImpl();
        List<DivisionBean> lstDivisions = divisionDAO.getAllDivisions("");
        try {
            if (validateDivisionName(txtDivisionNameAddDivision.getText())) {
                lblDivisionNameAddDivisionFrameValidation.setText("");
                for (DivisionBean divisionBean : lstDivisions) {
                    if (divisionBean.getDivision().equals(txtDivisionNameAddDivision.getText().trim())) {
                        lblDivisionNameAddDivisionFrameValidation.setText("Already Taken");
                        btnSaveAddDivision.setEnabled(false);
                    }
                }
            } else {
                lblDivisionNameAddDivisionFrameValidation.setText(msg);
                btnSaveAddDivision.setEnabled(false);
            }
            if (lblDivisionIdAddDivisionFrameValidation.getText().equals("") && lblDivisionNameAddDivisionFrameValidation.getText().equals("")) {
                btnSaveAddDivision.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtDivisionNameAddDivisionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDivisionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDivisionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDivisionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDivisionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDivisionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelAddDivision;
    private javax.swing.JButton btnSaveAddDivision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDivisionIdAddDivisionFrameValidation;
    private javax.swing.JLabel lblDivisionNameAddDivisionFrameValidation;
    public static javax.swing.JTextField txtDivisionIdAddDivision;
    public static javax.swing.JTextField txtDivisionNameAddDivision;
    // End of variables declaration//GEN-END:variables
}
