/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.ui.helper.common.RoleUIHelper;
import dpu.Validations;
import dpu.beans.admin.RoleBean;
import dpu.dao.admin.RoleDAO;
import dpu.dao.admin.impl.RoleDAOImpl;
import java.util.List;
import javax.swing.JOptionPane;

public class AddRoleFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddRole
     */
    String msg = "";
    RoleUIHelper roleUI = null;
    String addUpdateFlag = "";
    RoleBean roleBean;

    public AddRoleFrame() {
        initComponents();
        setLocationRelativeTo(null);
        roleUI = new RoleUIHelper();
        btnSaveAddRole.setEnabled(false);
        fillLabel();
    }

    public AddRoleFrame(RoleBean roleBean) {
        initComponents();
        roleUI = new RoleUIHelper();
        this.roleBean = roleBean;
        setLocationRelativeTo(null);
        addUpdateFlag = "update";
        showRecord(roleBean);
        btnSaveAddRole.setText("Update");
        btnSaveAddRole.setEnabled(true);
    }
    
    private void fillLabel() {
        lblRoleIdAddRoleFrameValidation.setText(" ");
        lblRoleNameAddRoleFrameValidation.setText(" ");
    }

    public boolean validateRoleId(String str) {
        if (Validations.isEmpty(str)) {
            msg = "Left Empty..!";
            return false;
        }
        if (Validations.hasNumerals(str)) {
            msg = "Only Numerics Allowed..!";
            return false;
        }
        if (Validations.hasSpace(str)) {
            msg = "Space Not Allowed..!";
            return false;
        }
        return true;
    }

    public boolean validateRoleName(String str) {
        if (Validations.isEmpty(str)) {
            msg = "Left Empty..!";
            return false;
        }
        if (Validations.hasAlphabets(str)) {
            msg = "Only Alphabets Allowed..!";
            return false;
        }
        if (Validations.hasSpace(str)) {
            msg = "Space Not Allowed..!";
            return false;
        }
        return true;
    }

    public void showRecord(RoleBean roleBean) {
        txtRoleIdAddRole.setText(String.valueOf(roleBean.getRoleId()));
        txtRoleNameAddRole.setText(roleBean.getRoleName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRoleIdAddRole = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRoleNameAddRole = new javax.swing.JTextField();
        btnSaveAddRole = new javax.swing.JButton();
        btnCancelAddRole = new javax.swing.JButton();
        lblRoleIdAddRoleFrameValidation = new javax.swing.JLabel();
        lblRoleNameAddRoleFrameValidation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Role Id");

        txtRoleIdAddRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleIdAddRoleActionPerformed(evt);
            }
        });
        txtRoleIdAddRole.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRoleIdAddRoleKeyReleased(evt);
            }
        });

        jLabel8.setText("Role Name");

        txtRoleNameAddRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleNameAddRoleActionPerformed(evt);
            }
        });
        txtRoleNameAddRole.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRoleNameAddRoleKeyReleased(evt);
            }
        });

        btnSaveAddRole.setText("Save");
        btnSaveAddRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddRoleActionPerformed(evt);
            }
        });

        btnCancelAddRole.setText("Cancel");
        btnCancelAddRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveAddRole, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelAddRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRoleNameAddRole)
                            .addComponent(txtRoleIdAddRole, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoleIdAddRoleFrameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoleNameAddRoleFrameValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelAddRole, btnSaveAddRole});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRoleIdAddRoleFrameValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtRoleIdAddRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtRoleNameAddRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoleNameAddRoleFrameValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveAddRole)
                    .addComponent(btnCancelAddRole))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoleIdAddRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleIdAddRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleIdAddRoleActionPerformed

    private void btnCancelAddRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddRoleActionPerformed
        dispose();
        roleUI.disable(true);
    }//GEN-LAST:event_btnCancelAddRoleActionPerformed

    private void btnSaveAddRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddRoleActionPerformed
        String msg = "";
        if (addUpdateFlag.equals("update")) {
            roleBean = new RoleBean();
            roleBean.setRoleId(Integer.parseInt(txtRoleIdAddRole.getText()));
            roleBean.setRoleName(txtRoleNameAddRole.getText());
            msg = roleUI.update(roleBean);
        } else {
            msg = roleUI.save();
        }
        JOptionPane.showMessageDialog(null, msg);
        dispose();
    }//GEN-LAST:event_btnSaveAddRoleActionPerformed

    private void txtRoleIdAddRoleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoleIdAddRoleKeyReleased
        RoleDAO roleDAO = new RoleDAOImpl();
        List<RoleBean> lstRoles = roleDAO.getAllRoles("");
        try {
            if (validateRoleId(txtRoleIdAddRole.getText())) {
                lblRoleIdAddRoleFrameValidation.setText("");
                for (RoleBean roleBean : lstRoles) {
                    if (roleBean.getRoleId() == Integer.parseInt(txtRoleIdAddRole.getText().trim())) {
                        lblRoleIdAddRoleFrameValidation.setText("Already Taken");
                        btnSaveAddRole.setEnabled(false);
                    }
                }
            } else {
                lblRoleIdAddRoleFrameValidation.setText(msg);
                btnSaveAddRole.setEnabled(false);
            }
            if (lblRoleIdAddRoleFrameValidation.getText().equals("") && lblRoleNameAddRoleFrameValidation.getText().equals("")) {
                btnSaveAddRole.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtRoleIdAddRoleKeyReleased

    private void txtRoleNameAddRoleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoleNameAddRoleKeyReleased
        RoleDAO roleDAO = new RoleDAOImpl();
        List<RoleBean> lstRoles = roleDAO.getAllRoles("");
        try {
            if (validateRoleName(txtRoleNameAddRole.getText())) {
                lblRoleNameAddRoleFrameValidation.setText("");
                for (RoleBean roleBean : lstRoles) {
                    if (roleBean.getRoleName().equals(txtRoleNameAddRole.getText().trim())) {
                        lblRoleNameAddRoleFrameValidation.setText("Already Taken");
                        btnSaveAddRole.setEnabled(false);
                    }
                }
            } else {
                lblRoleNameAddRoleFrameValidation.setText(msg);
                btnSaveAddRole.setEnabled(false);
            }
            if (lblRoleIdAddRoleFrameValidation.getText().equals("") && lblRoleNameAddRoleFrameValidation.getText().equals("")) {
                btnSaveAddRole.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtRoleNameAddRoleKeyReleased

    private void txtRoleNameAddRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleNameAddRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleNameAddRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRoleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCancelAddRole;
    public static javax.swing.JButton btnSaveAddRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblRoleIdAddRoleFrameValidation;
    private javax.swing.JLabel lblRoleNameAddRoleFrameValidation;
    public static javax.swing.JTextField txtRoleIdAddRole;
    public static javax.swing.JTextField txtRoleNameAddRole;
    // End of variables declaration//GEN-END:variables
}
