/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.ui.common.helper.DriverUIHelper;
import dpu.ui.shipper.TestShipperPannel;
import dpu.ui.terminal.TerminalPanel;
import java.awt.Container;
import java.awt.Toolkit;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author gagandeep.rana
 */
public class DatamaintenanceOptions extends javax.swing.JPanel {

    DriverUIHelper driverUIHelper = new DriverUIHelper();
    /**
     * Creates new form DatamaintenanceOptions
     */
    Container root = null;

    public DatamaintenanceOptions() {
        initComponents();
//        DPU.autowire(this);
        jInternalFrame1.putClientProperty("JInternalFrame.isPalette", Boolean.FALSE);
        jInternalFrame1.setMaximizable(false);
        jInternalFrame1.setIconifiable(false);
        jInternalFrame1.setClosable(false);
        jInternalFrame1.setBorder(null);
        BasicInternalFrameUI bi = (BasicInternalFrameUI) jInternalFrame1.getUI();
        bi.setNorthPane(null);
        bi.setEastPane(null);
        bi.setWestPane(null);
        bi.setSouthPane(null);
    }

    private void internalFrameSettings() {
        ArrangedMainFrame3.jInternalFrame1.setVisible(true);
        ArrangedMainFrame3.jInternalFrame1.setTitle("DPU - Customers");
        ArrangedMainFrame3.jInternalFrame1.putClientProperty("JInternalFrame.isPalette", Boolean.FALSE);
        ArrangedMainFrame3.jInternalFrame1.setMaximizable(false);
        ArrangedMainFrame3.jInternalFrame1.setIconifiable(false);
        ArrangedMainFrame3.jInternalFrame1.setClosable(false);
        ArrangedMainFrame3.jInternalFrame1.getContentPane().setVisible(false);
        ArrangedMainFrame3.jInternalFrame1.getContentPane().removeAll();
        ArrangedMainFrame3.jInternalFrame1.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        BasicInternalFrameUI bi = (BasicInternalFrameUI) ArrangedMainFrame3.jInternalFrame1.getUI();
        bi.setNorthPane(null);
        bi.setEastPane(null);
        bi.setWestPane(null);
        bi.setSouthPane(null);
        ArrangedMainFrame3.jInternalFrame1.setSize(Toolkit.getDefaultToolkit().getScreenSize());
//        ArrangedMainFrame3.jInternalFrame1.setBorder(null);
        root = ArrangedMainFrame3.jInternalFrame1.getContentPane();
        root.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        resourceMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setVisible(true);

        jMenu1.setText("Customers");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Prospects");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("<html>Shippers/Consignees</html>");
        jMenu3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenu3.setMinimumSize(new java.awt.Dimension(80, 19));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Border Crossing");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Outside Carriers");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Misc Vendors");
        jMenu6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Custom Brokers");
        jMenu7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu7MousePressed(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Standard Charges");
        jMenu8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu8MousePressed(evt);
            }
        });
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu9.setText("Jurisdictions");
        jMenu9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenuBar1.add(jMenu9);

        resourceMenu.setText("Resources");
        resourceMenu.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        resourceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceMenuActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Drivers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        resourceMenu.add(jMenuItem3);

        jMenuItem4.setText("Power Units");
        resourceMenu.add(jMenuItem4);

        jMenuBar1.add(resourceMenu);

        jMenu12.setText("Payroll Schedules");
        jMenu12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenuBar1.add(jMenu12);

        jMenu14.setText("Lists");
        jMenu14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jMenuItem1.setText("Type List");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem1);

        jMenuItem2.setText("Category List");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem2);

        jMenuItem7.setText("Equipment List");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem7);

        jMenuItem8.setText("Terminals List");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem8);

        jMenuItem9.setText("Payment Terms List");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem9);

        jMenuBar1.add(jMenu14);

        jMenu15.setText("Master Orders");
        jMenu15.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenuBar1.add(jMenu15);

        jMenu16.setText("TravelTimes");
        jMenu16.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jMenuBar1.add(jMenu16);

        jMenu17.setText("Others");
        jMenu17.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jMenuItem5.setText("Sales Person");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem5);

        jMenuItem6.setText("Standard Templates");
        jMenu17.add(jMenuItem6);

        jMenuBar1.add(jMenu17);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1297, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        internalFrameSettings();
        CompanyPanel1 testCompanyPanel = new CompanyPanel1();
        testCompanyPanel.setBounds(0, 0, getWidth(), getHeight()-150);
        root.add(testCompanyPanel);
        root.setVisible(true);
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed

    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed

    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        internalFrameSettings();
        TestShipperPannel testShippersPanel = new TestShipperPannel();
        testShippersPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(testShippersPanel);
        root.setVisible(true);
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MousePressed
        internalFrameSettings();
        CustomBrokersPanel testCustomBrokersPanel = new CustomBrokersPanel();
        testCustomBrokersPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(testCustomBrokersPanel);
        root.setVisible(true);
    }//GEN-LAST:event_jMenu7MousePressed

    private void jMenu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MousePressed
        internalFrameSettings();
        StandardCharges testStandardCharges = new StandardCharges();
        testStandardCharges.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(testStandardCharges);
        root.setVisible(true);
    }//GEN-LAST:event_jMenu8MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        internalFrameSettings();
        TypePanel typePanel = new TypePanel();
        typePanel.setBounds(0, 0, getWidth(), getHeight());
        root.add(typePanel);
        root.setVisible(true);
     }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        internalFrameSettings();
        CategoryPanel categoryPanel = new CategoryPanel();
        categoryPanel.setBounds(0, 0, getWidth(), getHeight() - 150);
        root.add(categoryPanel);
        root.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        internalFrameSettings();
        EquipmentPanel equipmentPanel = new EquipmentPanel();
        equipmentPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(equipmentPanel);
        root.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        internalFrameSettings();
        TerminalPanel terminalPanel = new TerminalPanel();
        terminalPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(terminalPanel);
        root.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        internalFrameSettings();
        PaymentTermsPanel paymentTermsPanel = new PaymentTermsPanel();
        paymentTermsPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(paymentTermsPanel);
        root.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        internalFrameSettings();
        SalesPersonPanel salesPersonPanel = new SalesPersonPanel();
        salesPersonPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(salesPersonPanel);
        root.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        internalFrameSettings();
        DriverPanel driverPanel = new DriverPanel();
        driverPanel.setBounds(0, 0, getWidth() , getHeight() - 50);
        root.add(driverPanel);
        root.setVisible(true);
        driverUIHelper.showAllDrivers();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void resourceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resourceMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu resourceMenu;
    // End of variables declaration//GEN-END:variables
}
