/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.ui.shipper.TestShipperPannel;
import java.awt.Container;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author gagandeep.rana
 */
@Component
public class Datamaintenance extends javax.swing.JPanel {

    /**
     * Creates new form Datamaintenance
     */
    Container root = null;

    @Autowired
    TestCompanyPanel testCompanyPanel;

    public Datamaintenance() {
        initComponents();
        setButtonContentArea();
    }

    private void setButtonContentArea() {
        btnCustomers.setContentAreaFilled(false);
        btnCustomBroker.setContentAreaFilled(false);
        btnStandardTemplates.setContentAreaFilled(false);
        btnStandardCharges.setContentAreaFilled(false);
        btnPayrollSchedule.setContentAreaFilled(false);
        btnMiscVendors.setContentAreaFilled(false);
        btnOutsideCarriers.setContentAreaFilled(false);
        btnBorderCrossing.setContentAreaFilled(false);
        btnShippers.setContentAreaFilled(false);
        btnMasterOrders.setContentAreaFilled(false);
        btnSalesPerson.setContentAreaFilled(false);
        btnResources.setContentAreaFilled(false);
        btnCustomers.setBorderPainted(false);
        btnStandardTemplates.setBorderPainted(false);
        btnPayrollSchedule.setBorderPainted(false);
        btnCustomBroker.setBorderPainted(false);
        btnMiscVendors.setBorderPainted(false);
        btnOutsideCarriers.setBorderPainted(false);
        btnBorderCrossing.setBorderPainted(false);
        btnShippers.setBorderPainted(false);
        btnMasterOrders.setBorderPainted(false);
        btnStandardCharges.setBorderPainted(false);
        btnSalesPerson.setBorderPainted(false);
        btnResources.setBorderPainted(false);
    }

    private void internalFrameSettings() {
        ArrangedMainFrame3.jInternalFrame1.setVisible(true);
        ArrangedMainFrame3.jInternalFrame1.setTitle("DPU - Customers");
        ArrangedMainFrame3.jInternalFrame1.putClientProperty("JInternalFrame.isPalette", Boolean.FALSE);
        ArrangedMainFrame3.jInternalFrame1.setMaximizable(false);
        ArrangedMainFrame3.jInternalFrame1.setIconifiable(false);
        ArrangedMainFrame3.jInternalFrame1.setClosable(false);
        ArrangedMainFrame3.jInternalFrame1.getContentPane().setVisible(false);
        ArrangedMainFrame3.jInternalFrame1.getContentPane().removeAll();
        ArrangedMainFrame3.jInternalFrame1.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        BasicInternalFrameUI bi = (BasicInternalFrameUI) ArrangedMainFrame3.jInternalFrame1.getUI();
        bi.setNorthPane(null);
        bi.setEastPane(null);
        bi.setWestPane(null);
        bi.setSouthPane(null);
        ArrangedMainFrame3.jInternalFrame1.setBorder(null);
        root = ArrangedMainFrame3.jInternalFrame1.getContentPane();
        root.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        btnCustomers = new javax.swing.JButton();
        btnStandardTemplates = new javax.swing.JButton();
        btnCustomBroker = new javax.swing.JButton();
        btnStandardCharges = new javax.swing.JButton();
        btnPayrollSchedule = new javax.swing.JButton();
        btnMiscVendors = new javax.swing.JButton();
        btnOutsideCarriers = new javax.swing.JButton();
        btnBorderCrossing = new javax.swing.JButton();
        btnShippers = new javax.swing.JButton();
        btnSalesPerson = new javax.swing.JButton();
        btnResources = new javax.swing.JButton();
        btnMasterOrders = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(487, 37));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator9.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator10.setPreferredSize(new java.awt.Dimension(2, 23));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator11.setPreferredSize(new java.awt.Dimension(2, 23));

        jLabel28.setFont(new java.awt.Font("Vijaya", 1, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dpu/ui/common/Cross.png"))); // NOI18N
        jLabel28.setToolTipText("Close Menubar...");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        btnCustomers.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomers.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(102, 102, 102));
        btnCustomers.setText("Customers");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnStandardTemplates.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnStandardTemplates.setForeground(new java.awt.Color(102, 102, 102));
        btnStandardTemplates.setText("<html>Standard Templates</html>");

        btnCustomBroker.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCustomBroker.setForeground(new java.awt.Color(102, 102, 102));
        btnCustomBroker.setText("<html>Custom Broker</html>");
        btnCustomBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomBrokerActionPerformed(evt);
            }
        });

        btnStandardCharges.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnStandardCharges.setForeground(new java.awt.Color(102, 102, 102));
        btnStandardCharges.setText("<html>Standard Charges</html>");
        btnStandardCharges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStandardChargesActionPerformed(evt);
            }
        });

        btnPayrollSchedule.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPayrollSchedule.setForeground(new java.awt.Color(102, 102, 102));
        btnPayrollSchedule.setText("<html>Payroll Schedule</html>");

        btnMiscVendors.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMiscVendors.setForeground(new java.awt.Color(102, 102, 102));
        btnMiscVendors.setText("<html>Misc Vendors</html>");

        btnOutsideCarriers.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnOutsideCarriers.setForeground(new java.awt.Color(102, 102, 102));
        btnOutsideCarriers.setText("<html>Outside Carriers</html>");
        btnOutsideCarriers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutsideCarriersActionPerformed(evt);
            }
        });

        btnBorderCrossing.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBorderCrossing.setForeground(new java.awt.Color(102, 102, 102));
        btnBorderCrossing.setText("<html>Border Crossing</html>");

        btnShippers.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnShippers.setForeground(new java.awt.Color(102, 102, 102));
        btnShippers.setText("Shippers");
        btnShippers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShippersActionPerformed(evt);
            }
        });

        btnSalesPerson.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalesPerson.setForeground(new java.awt.Color(102, 102, 102));
        btnSalesPerson.setText("<html>Sales Person</html>");

        btnResources.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnResources.setForeground(new java.awt.Color(102, 102, 102));
        btnResources.setText("Resources");
        btnResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResourcesActionPerformed(evt);
            }
        });

        btnMasterOrders.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMasterOrders.setForeground(new java.awt.Color(102, 102, 102));
        btnMasterOrders.setText("<html>Master Orders</html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnCustomers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStandardTemplates, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPayrollSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMiscVendors, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutsideCarriers, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorderCrossing, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShippers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMasterOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStandardCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalesPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResources)
                .addGap(313, 313, 313)
                .addComponent(jLabel28)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayrollSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStandardTemplates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnResources, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalesPerson, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStandardCharges, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShippers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorderCrossing, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMiscVendors, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCustomBroker, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnOutsideCarriers, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCustomers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnMasterOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomBrokerActionPerformed
        internalFrameSettings();
        TestCustomBrokersPanel testCustomBrokersPanel = new TestCustomBrokersPanel();
        testCustomBrokersPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(testCustomBrokersPanel);
        root.setVisible(true);
    }//GEN-LAST:event_btnCustomBrokerActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        internalFrameSettings();
        testCompanyPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(testCompanyPanel);
        root.setVisible(true);
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnStandardChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStandardChargesActionPerformed
        internalFrameSettings();

        TestStandardCharges testStandardCharges = new TestStandardCharges();
        testStandardCharges.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(testStandardCharges);
        root.setVisible(true);
    }//GEN-LAST:event_btnStandardChargesActionPerformed

    private void btnResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResourcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResourcesActionPerformed

    private void btnOutsideCarriersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutsideCarriersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOutsideCarriersActionPerformed

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void btnShippersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShippersActionPerformed
        internalFrameSettings();
        TestShipperPannel testShippersPanel = new TestShipperPannel();
        testShippersPanel.setBounds(0, 0, getWidth() - 12, getHeight() - 10);
        root.add(testShippersPanel);
        root.setVisible(true);
    }//GEN-LAST:event_btnShippersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorderCrossing;
    private javax.swing.JButton btnCustomBroker;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnMasterOrders;
    private javax.swing.JButton btnMiscVendors;
    private javax.swing.JButton btnOutsideCarriers;
    private javax.swing.JButton btnPayrollSchedule;
    private javax.swing.JButton btnResources;
    private javax.swing.JButton btnSalesPerson;
    private javax.swing.JButton btnShippers;
    private javax.swing.JButton btnStandardCharges;
    private javax.swing.JButton btnStandardTemplates;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
