/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.beans.admin.CompanyBean;
import dpu.entity.admin.Driver;
import static dpu.ui.common.CompanyPanel1.tblCompany;
import dpu.ui.common.helper.CompanyUIHelper;
import dpu.ui.common.helper.DriverUIHelper;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Durga
 */
public class DriverPanel extends javax.swing.JPanel {
    
    
     
     
    DriverUIHelper driverUIHelper = new DriverUIHelper();
    /**
     * Creates new form DriverPanel
     */
    public DriverPanel() {
         
        
        initComponents();
        
            setSize(Toolkit.getDefaultToolkit().getScreenSize());
        driverTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
         driverTable.setPreferredScrollableViewportSize(Toolkit.getDefaultToolkit().getScreenSize());
         
        driverTable.setModel(new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    });
       //sort();
    }
    
public void sort(){
    TableRowSorter<TableModel> sorter = new TableRowSorter<>(driverTable.getModel());
driverTable.setRowSorter(sorter);
List<RowSorter.SortKey> sortKeys = new ArrayList<>();
 
int columnIndexToSort = 1;
sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.ASCENDING));
 
sorter.setSortKeys(sortKeys);
sorter.sort();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtQuickFilter = new javax.swing.JTextField();
        btnQuickFilter = new javax.swing.JButton();
        cbShowAll = new javax.swing.JCheckBox();
        btnPrint = new javax.swing.JButton();
        btnUpdateDriver = new javax.swing.JButton();
        btnDeleteDriver = new javax.swing.JButton();
        btnEmail = new javax.swing.JButton();
        btnAddDriver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        driverTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };

        jLabel1.setText("QuickFilter");

        btnQuickFilter.setText("GO");
        btnQuickFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickFilterActionPerformed(evt);
            }
        });

        cbShowAll.setText("Show All");
        cbShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowAllActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");

        btnUpdateDriver.setText("Edit");
        btnUpdateDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDriverActionPerformed(evt);
            }
        });

        btnDeleteDriver.setText("Delete");
        btnDeleteDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDriverActionPerformed(evt);
            }
        });

        btnEmail.setText("E-Mail");

        btnAddDriver.setText("+");
        btnAddDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAddDriver.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/dpu/ui/common/Add-Images.png"))); // NOI18N
        btnAddDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDriverActionPerformed(evt);
            }
        });

        driverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Driver Code                                                                ", "First Name", "Last Name", "Address", "Unit", "City", "Pvs", "Postal", "Email", "Home", "FaxNo", "Cellular", "Pager", "Division", "Terminal", "Category", "Role", "Status", "ClassId"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        }
    );
    jScrollPane1.setViewportView(driverTable);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnAddDriver)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtQuickFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnQuickFilter)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(cbShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnUpdateDriver)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnDeleteDriver)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnEmail)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnPrint)
                    .addGap(0, 644, Short.MAX_VALUE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(1, 1, 1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnDeleteDriver)
                .addComponent(btnEmail)
                .addComponent(btnUpdateDriver)
                .addComponent(btnPrint)
                .addComponent(cbShowAll)
                .addComponent(btnQuickFilter)
                .addComponent(txtQuickFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(btnAddDriver))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(78, Short.MAX_VALUE))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddDriver, btnDeleteDriver, btnEmail, btnPrint, btnQuickFilter, btnUpdateDriver, cbShowAll, jLabel1, txtQuickFilter});

    }// </editor-fold>//GEN-END:initComponents

    private void cbShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowAllActionPerformed
        // TODO add your handling code here:
        if(cbShowAll.isSelected() == true){
            driverUIHelper.showAll();
        }
         else{
            driverUIHelper.QuickFilterDrivers();
        }
    }//GEN-LAST:event_cbShowAllActionPerformed

    private void btnAddDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDriverActionPerformed
        // TODO add your handling code here:
        AddDriverFrame addDriverFrame = new AddDriverFrame();
        addDriverFrame.setVisible(true);
    }//GEN-LAST:event_btnAddDriverActionPerformed

    private void btnDeleteDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDriverActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)driverTable.getModel();
        // get Selected Row Index
        try {
            int selectedRowIndex = driverTable.getSelectedRow();
            System.out.println("Selected Row Number :"+selectedRowIndex);
            
            String driverCode = model.getValueAt(selectedRowIndex, 0).toString();
            System.out.println("driverCode :"+driverCode);
            //JOptionPane.showMessageDialog(null, "you want to remove");
            model.removeRow(selectedRowIndex);
            driverUIHelper.deleteDriver(driverCode);
            
            
        } catch(Exception e) {
           // JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDeleteDriverActionPerformed

    private void btnUpdateDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDriverActionPerformed
        // TODO add your handling code here:
        String value = "Update Driver";
        
        AddDriverFrame addDriverFrame = new AddDriverFrame(value);
        addDriverFrame.setVisible(true);
         
         
    }//GEN-LAST:event_btnUpdateDriverActionPerformed

    private void btnQuickFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickFilterActionPerformed
        // TODO add your handling code here:
        driverUIHelper.QuickFilterDrivers();
    }//GEN-LAST:event_btnQuickFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDriver;
    private javax.swing.JButton btnDeleteDriver;
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnQuickFilter;
    private javax.swing.JButton btnUpdateDriver;
    public static javax.swing.JCheckBox cbShowAll;
    public static javax.swing.JTable driverTable;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtQuickFilter;
    // End of variables declaration//GEN-END:variables
}
