/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.ui.common.helper.ClassUIHelper;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import properties.ReadFromPropertiesFile;

/**
 *
 * @author gagandeep.rana
 */
public class TestClassPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestClassPanel
     */
    ClassUIHelper classUIHelper = null;

    public TestClassPanel() {
        try {
            initComponents();
            btnClearManageClass.setContentAreaFilled(false);
            tblClass.setPreferredSize(new Dimension(300, 300));
            btnClearManageClass.setIcon(new ImageIcon(ReadFromPropertiesFile.imagePath + "Print.png"));
            classUIHelper = new ClassUIHelper();
            classUIHelper.generateTable();
        } catch (Exception e) {
            System.out.println("TestClassPanel: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtClassSearch = new javax.swing.JTextField();
        btnClearManageClass = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClass = new javax.swing.JTable();
        btnAddManageClass = new javax.swing.JLabel();

        txtClassSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClassSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClassSearchKeyTyped(evt);
            }
        });

        btnClearManageClass.setIcon(new javax.swing.ImageIcon("E:\\gitrepository\\DPU\\images\\Print.png")); // NOI18N
        btnClearManageClass.setBorder(null);
        btnClearManageClass.setBorderPainted(false);
        btnClearManageClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearManageClassActionPerformed(evt);
            }
        });

        tblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Title"
            }
        ));
        jScrollPane3.setViewportView(tblClass);

        btnAddManageClass.setIcon(new javax.swing.ImageIcon("E:\\gitrepository\\DPU\\images\\Add.png")); // NOI18N
        btnAddManageClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddManageClassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddManageClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClassSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearManageClass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 950, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClearManageClass, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddManageClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtClassSearch)
                    .addComponent(btnClearManageClass, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddManageClass, btnClearManageClass, jLabel2, txtClassSearch});

    }// </editor-fold>//GEN-END:initComponents

    private void txtClassSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClassSearchKeyReleased

        classUIHelper.generateTable();
    }//GEN-LAST:event_txtClassSearchKeyReleased

    private void txtClassSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClassSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassSearchKeyTyped

    private void btnClearManageClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearManageClassActionPerformed
    }//GEN-LAST:event_btnClearManageClassActionPerformed

    private void btnAddManageClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddManageClassMouseClicked
        classUIHelper.disable(false);
        AddClassFrame addClassFrame = new AddClassFrame();
        addClassFrame.setVisible(true);
    }//GEN-LAST:event_btnAddManageClassMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel btnAddManageClass;
    public static javax.swing.JButton btnClearManageClass;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable tblClass;
    public static javax.swing.JTextField txtClassSearch;
    // End of variables declaration//GEN-END:variables
}
