/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.ui.common.helper.TrackingUIHelper;

/**
 *
 * @author gagandeep.rana
 */
public class TestTrackingPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestTrackingPanel
     */
    TrackingUIHelper trackingUIHelper = null;

    public TestTrackingPanel() {
        initComponents();
        trackingUIHelper = new TrackingUIHelper();
        trackingUIHelper.generateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddManageTracking = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTrackingSearch = new javax.swing.JTextField();
        btnClearManageTracking = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblTracking = new javax.swing.JTable();

        btnAddManageTracking.setText("+");
        btnAddManageTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddManageTrackingActionPerformed(evt);
            }
        });

        jLabel7.setText("Search");

        txtTrackingSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTrackingSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrackingSearchKeyTyped(evt);
            }
        });

        btnClearManageTracking.setText("Clear");
        btnClearManageTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearManageTrackingActionPerformed(evt);
            }
        });

        tblTracking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Title"
            }
        ));
        jScrollPane8.setViewportView(tblTracking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddManageTracking)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTrackingSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearManageTracking))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddManageTracking)
                    .addComponent(jLabel7)
                    .addComponent(btnClearManageTracking)
                    .addComponent(txtTrackingSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddManageTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddManageTrackingActionPerformed
        trackingUIHelper.disable(false);
        AddTrackingFrame addTrackingFrame = new AddTrackingFrame();
        addTrackingFrame.setVisible(true);
    }//GEN-LAST:event_btnAddManageTrackingActionPerformed

    private void txtTrackingSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrackingSearchKeyReleased
        trackingUIHelper.generateTable();
    }//GEN-LAST:event_txtTrackingSearchKeyReleased

    private void txtTrackingSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrackingSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrackingSearchKeyTyped

    private void btnClearManageTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearManageTrackingActionPerformed
        txtTrackingSearch.setText("");
        trackingUIHelper.generateTable();
    }//GEN-LAST:event_btnClearManageTrackingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAddManageTracking;
    public static javax.swing.JButton btnClearManageTracking;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JTable tblTracking;
    public static javax.swing.JTextField txtTrackingSearch;
    // End of variables declaration//GEN-END:variables
}
