/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

import dpu.reports.common.JasperReportGenerator;
import dpu.ui.helper.common.ClassUIHelper;
import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author gagandeep.rana
 */
public class TestClassPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestClassPanel
     */
    ClassUIHelper classUIHelper = null;
    
    public TestClassPanel() {
        
        initComponents();
        btnClearManageClass.setContentAreaFilled(false);
        btnClearManageClass.setAction(new ShowWaitAction(""));
        btnClearManageClass.setIcon(new ImageIcon("src\\dpu\\ui\\common\\Print.png"));
        classUIHelper = new ClassUIHelper();
        classUIHelper.generateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtClassSearch = new javax.swing.JTextField();
        btnClearManageClass = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClass = new javax.swing.JTable();
        btnAddManageClass = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dpu/ui/common/Search.png"))); // NOI18N

        txtClassSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClassSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClassSearchKeyTyped(evt);
            }
        });

        btnClearManageClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dpu/ui/common/Print.png"))); // NOI18N
        btnClearManageClass.setBorder(null);
        btnClearManageClass.setBorderPainted(false);
        btnClearManageClass.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/dpu/ui/common/Print.png"))); // NOI18N
        btnClearManageClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearManageClassActionPerformed(evt);
            }
        });

        tblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Title"
            }
        ));
        jScrollPane3.setViewportView(tblClass);

        btnAddManageClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dpu/ui/common/Add.png"))); // NOI18N
        btnAddManageClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddManageClassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddManageClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClassSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearManageClass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClearManageClass, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddManageClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtClassSearch)
                    .addComponent(btnClearManageClass, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddManageClass, btnClearManageClass, jLabel2, txtClassSearch});

    }// </editor-fold>//GEN-END:initComponents

    private void txtClassSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClassSearchKeyReleased
        
        classUIHelper.generateTable();
    }//GEN-LAST:event_txtClassSearchKeyReleased

    private void txtClassSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClassSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassSearchKeyTyped

    private void btnClearManageClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearManageClassActionPerformed
    }//GEN-LAST:event_btnClearManageClassActionPerformed

    private void btnAddManageClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddManageClassMouseClicked
        classUIHelper.disable(false);
        AddClassFrame addClassFrame = new AddClassFrame();
        addClassFrame.setVisible(true);
    }//GEN-LAST:event_btnAddManageClassMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel btnAddManageClass;
    public static javax.swing.JButton btnClearManageClass;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable tblClass;
    public static javax.swing.JTextField txtClassSearch;
    // End of variables declaration//GEN-END:variables
}

class ShowWaitAction extends AbstractAction {
    
    protected static final long SLEEP_TIME = 2 * 1000;
    
    public ShowWaitAction(String name) {
        super(name);
    }
    
    @Override
    public void actionPerformed(ActionEvent evt) {
        SwingWorker<Void, Void> mySwingWorker = new SwingWorker<Void, Void>() {
            
            @Override
            protected Void doInBackground() throws Exception {
                // mimic some long-running process here...
                Thread.sleep(SLEEP_TIME);
                return null;
            }
        };
        
        Window win = SwingUtilities.getWindowAncestor((AbstractButton) evt.getSource());
        final JDialog dialog = new JDialog(win, "", Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setUndecorated(true);
        
        mySwingWorker.addPropertyChangeListener(new PropertyChangeListener() {
            
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals("state")) {
                    if (evt.getNewValue() == SwingWorker.StateValue.DONE) {
                        JasperReportGenerator.generateReport("ClassReport.jrxml");
                        dialog.dispose();
                    }
                }
            }
        });
        mySwingWorker.execute();
//        JProgressBar progressBar = new JProgressBar();
//        progressBar.setIndeterminate(true);
        JPanel panel = new JPanel(new BorderLayout());
//        panel.add(progressBar, BorderLayout.CENTER);
//        panel.add(new JLabel("Please wait......."), BorderLayout.PAGE_START);
        JLabel jLabel = new JLabel(new ImageIcon("src\\dpu\\ui\\common\\Wait.gif"));
        panel.add(jLabel);
        dialog.add(panel);
        TestClassPanel testClassPanel = new TestClassPanel();
        testClassPanel.setEnabled(false);
        dialog.pack();
        dialog.setLocationRelativeTo(win);
        dialog.setVisible(true);
        
    }
}
