/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.common;

/**
 *
 * @author gagandeep.rana
 */
public class TestJurisdictionPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestJurisdictionPanel
     */
    public TestJurisdictionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddManageJurisdiction = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtJurisdictionSearch = new javax.swing.JTextField();
        btnClearManageJurisdiction = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblJurisdiction = new javax.swing.JTable();

        btnAddManageJurisdiction.setText("+");
        btnAddManageJurisdiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddManageJurisdictionActionPerformed(evt);
            }
        });

        jLabel11.setText("Search");

        txtJurisdictionSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJurisdictionSearchKeyReleased(evt);
            }
        });

        btnClearManageJurisdiction.setText("Clear");
        btnClearManageJurisdiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearManageJurisdictionActionPerformed(evt);
            }
        });

        tblJurisdiction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Title"
            }
        ));
        jScrollPane10.setViewportView(tblJurisdiction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddManageJurisdiction)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtJurisdictionSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearManageJurisdiction)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtJurisdictionSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearManageJurisdiction)
                    .addComponent(btnAddManageJurisdiction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddManageJurisdictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddManageJurisdictionActionPerformed
//        jurisdictionUIHelper.disable(false);
//        AddJurisdictionFrame addJurisdictionFrame = new AddJurisdictionFrame();
//        addJurisdictionFrame.setVisible(true);
    }//GEN-LAST:event_btnAddManageJurisdictionActionPerformed

    private void txtJurisdictionSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJurisdictionSearchKeyReleased
//        jurisdictionUIHelper.generateTable();
    }//GEN-LAST:event_txtJurisdictionSearchKeyReleased

    private void btnClearManageJurisdictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearManageJurisdictionActionPerformed
//        txtJurisdictionSearch.setText("");
//        jurisdictionUIHelper.generateTable();
    }//GEN-LAST:event_btnClearManageJurisdictionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAddManageJurisdiction;
    public static javax.swing.JButton btnClearManageJurisdiction;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JScrollPane jScrollPane10;
    public static javax.swing.JTable tblJurisdiction;
    public static javax.swing.JTextField txtJurisdictionSearch;
    // End of variables declaration//GEN-END:variables
}
