/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.terminal;


import dpu.beans.admin.TerminalBean;
import dpu.dao.admin.TerminalDAO;
import dpu.dao.admin.impl.TerminalDAOImpl;
import dpu.ui.common.helper.TerminalUIHelper;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import properties.ReadFromPropertiesFile;

/**
 *
 * @author sunny
 */
public class TerminalPanel extends javax.swing.JPanel {

    /**
     * S
     * Creates new form TestTerminal
     */
    TerminalUIHelper terminalservices = null;
    TerminalDAO terminalDAO = null;
    String printImage = "";

    public TerminalPanel() {
        initComponents();
        terminalservices = new TerminalUIHelper();
        terminalDAO = new TerminalDAOImpl();
        System.out.println("TerminalPanel.txtSearch.getText() " + TerminalPanel.txtSearch.getText().toString());
        TerminalUIHelper.lstTerminals = terminalDAO.getAllTerminals(TerminalPanel.txtSearch.getText());
        System.out.println("size" + TerminalUIHelper.lstTerminals.size());
        terminalservices.generateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblTerminal = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        setForeground(new java.awt.Color(204, 204, 204));
        setAlignmentX(0.0F);

        tblTerminal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Terminal", "Facility", "Location"
            }
        ));
        tblTerminal.setToolTipText("Terminal Listing");
        tblTerminal.setGridColor(new java.awt.Color(153, 153, 153));
        tblTerminal.setPreferredSize(new java.awt.Dimension(225, 350));
        tblTerminal.setShowHorizontalLines(false);
        tblTerminal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblTerminalMouseReleased(evt);
            }
        });
        jScrollPane9.setViewportView(tblTerminal);

        btnAdd.setText("+");
        btnAdd.setToolTipText("Add New Terminal");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Search");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setToolTipText("Print");
        btnPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update.png"))); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.setToolTipText("Edit New Terminal");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete New Terminal");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Go");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(51, 23));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnDelete))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnPrint))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnUpdate))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnDelete))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void tblTerminalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTerminalMouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            final MouseEvent evt1 = evt;
            jPopupMenu1 = new JPopupMenu();
            JMenuItem menuItem1 = new JMenuItem("Add New Terminal");
            menuItem1.setIcon(new ImageIcon(ReadFromPropertiesFile.imagePath + "New-Customer.png"));
            menuItem1.setIconTextGap(5);

            JMenuItem menuItem2 = new JMenuItem("Edit Terminal");
            menuItem2.setIcon(new ImageIcon(ReadFromPropertiesFile.imagePath + "New-Customer.png"));
            menuItem2.setIconTextGap(5);
            JMenuItem menuItem3 = new JMenuItem("Delete Terminal");
            menuItem3.setIcon(new ImageIcon(ReadFromPropertiesFile.imagePath + "Delete.png"));
            menuItem3.setIconTextGap(5);
            jPopupMenu1.add(menuItem1);
            jPopupMenu1.add(menuItem2);
            jPopupMenu1.add(menuItem3);

            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());

            menuItem1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    TerminalUIHelper.addUpdateFlag = "add";
                    AddTerminal addTerminalFrame = new AddTerminal();
                    addTerminalFrame.setVisible(true);
                }
            });

            menuItem2.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    TerminalUIHelper.addUpdateFlag = "update";
                    TerminalBean terminalBean = new TerminalBean();
                    terminalBean = TerminalUIHelper.lstTerminals.get(tblTerminal.rowAtPoint(evt1.getPoint()));
                    TerminalUIHelper.terminalId = terminalBean.getTerminalId();
                    AddTerminal addTerminalFrame = new AddTerminal(terminalBean);
                    addTerminalFrame.setVisible(true);
                }
            });

            menuItem3.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    TerminalBean terminalBean = TerminalUIHelper.lstTerminals.get(tblTerminal.rowAtPoint(evt1.getPoint()));
                    terminalservices.delete(terminalBean.getTerminalId());
                }
            });
        } else if (evt.getButton() == 1) {
            tblTerminal.setSelectionBackground(Color.GREEN);
        }
    }//GEN-LAST:event_tblTerminalMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int terminalIdToBeDeleted = TerminalUIHelper.lstTerminals.get(tblTerminal.getSelectedRow()).getTerminalId();
        String msg = terminalservices.delete(terminalIdToBeDeleted);
        JOptionPane.showMessageDialog(null, msg);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        TerminalBean terminalBean = TerminalUIHelper.lstTerminals.get(tblTerminal.getSelectedRow());
        TerminalUIHelper.terminalId = terminalBean.getTerminalId();
        TerminalUIHelper.addUpdateFlag = "update";
        AddTerminal addTerminalFrame = new AddTerminal(terminalBean);
        addTerminalFrame.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        TerminalUIHelper.lstTerminals = terminalDAO.getAllTerminals(TerminalPanel.txtSearch.getText());
        terminalservices.generateTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        TerminalUIHelper.addUpdateFlag = "add";
        AddTerminal addTerminalFrame = new AddTerminal();
        addTerminalFrame.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdd;
    public static javax.swing.JButton btnDelete;
    public static javax.swing.JButton btnPrint;
    public static javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    public static javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JTable tblTerminal;
    public static javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
