/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dpu.ui.terminal;


import dpu.beans.admin.TerminalBean;
import dpu.dao.admin.TerminalDAO;
import dpu.dao.admin.impl.TerminalDAOImpl;
import dpu.ui.common.helper.TerminalUIHelper;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import properties.ReadFromPropertiesFile;

/**
 *
 * @author sunny
 */
public class TerminalPanel extends javax.swing.JPanel {

    /**
     * S
     * Creates new form TestTerminal
     */
    TerminalUIHelper terminalservices = null;
    TerminalDAO terminalDAO = null;
    String printImage = "";

    public TerminalPanel() {
        initComponents();
        terminalservices = new TerminalUIHelper();
        terminalDAO = new TerminalDAOImpl();
        System.out.println("TerminalPanel.txtSearch.getText() " + TerminalPanel.txtSearch.getText().toString());
        TerminalUIHelper.lstTerminals = terminalDAO.getAllTerminals(TerminalPanel.txtSearch.getText());
        System.out.println("size" + TerminalUIHelper.lstTerminals.size());
        terminalservices.generateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblTerminal = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        setForeground(new java.awt.Color(204, 204, 204));
        setAlignmentX(0.0F);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTerminal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Terminal", "Facility", "Location"
            }
        ));
        tblTerminal.setToolTipText("Terminal Listing");
        tblTerminal.setGridColor(new java.awt.Color(153, 153, 153));
        tblTerminal.setPreferredSize(new java.awt.Dimension(225, 350));
        tblTerminal.setShowHorizontalLines(false);
        tblTerminal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblTerminalMouseReleased(evt);
            }
        });
        jScrollPane9.setViewportView(tblTerminal);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 660, 800));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("+");
        btnAdd.setToolTipText("Add New Terminal");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 36, 23));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Search");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, -1, -1));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 13, 150, -1));

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setToolTipText("Print");
        btnPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 63, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update.png"))); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.setToolTipText("Edit New Terminal");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 63, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete New Terminal");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Go");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(51, 23));
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 670, 40));
        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void tblTerminalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTerminalMouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            final MouseEvent evt1 = evt;
            jPopupMenu1 = new JPopupMenu();
            JMenuItem menuItem1 = new JMenuItem("Add New Terminal");
            menuItem1.setIcon(new ImageIcon(ReadFromPropertiesFile.imagePath + "New-Customer.png"));
            menuItem1.setIconTextGap(5);

            JMenuItem menuItem2 = new JMenuItem("Edit Terminal");
            menuItem2.setIcon(new ImageIcon(ReadFromPropertiesFile.imagePath + "New-Customer.png"));
            menuItem2.setIconTextGap(5);
            JMenuItem menuItem3 = new JMenuItem("Delete Terminal");
            menuItem3.setIcon(new ImageIcon(ReadFromPropertiesFile.imagePath + "Delete.png"));
            menuItem3.setIconTextGap(5);
            jPopupMenu1.add(menuItem1);
            jPopupMenu1.add(menuItem2);
            jPopupMenu1.add(menuItem3);

            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());

            menuItem1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    TerminalUIHelper.addUpdateFlag = "add";
                    AddTerminal addTerminalFrame = new AddTerminal();
                    addTerminalFrame.setVisible(true);
                }
            });

            menuItem2.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    TerminalUIHelper.addUpdateFlag = "update";
                    TerminalBean terminalBean = new TerminalBean();
                    terminalBean = TerminalUIHelper.lstTerminals.get(tblTerminal.rowAtPoint(evt1.getPoint()));
                    TerminalUIHelper.terminalId = terminalBean.getTerminalId();
                    AddTerminal addTerminalFrame = new AddTerminal(terminalBean);
                    addTerminalFrame.setVisible(true);
                }
            });

            menuItem3.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    TerminalBean terminalBean = TerminalUIHelper.lstTerminals.get(tblTerminal.rowAtPoint(evt1.getPoint()));
                    terminalservices.delete(terminalBean.getTerminalId());
                }
            });
        } else if (evt.getButton() == 1) {
            tblTerminal.setSelectionBackground(Color.GREEN);
        }
    }//GEN-LAST:event_tblTerminalMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int terminalIdToBeDeleted = TerminalUIHelper.lstTerminals.get(tblTerminal.getSelectedRow()).getTerminalId();
        String msg = terminalservices.delete(terminalIdToBeDeleted);
        JOptionPane.showMessageDialog(null, msg);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        TerminalBean terminalBean = TerminalUIHelper.lstTerminals.get(tblTerminal.getSelectedRow());
        TerminalUIHelper.terminalId = terminalBean.getTerminalId();
        TerminalUIHelper.addUpdateFlag = "update";
        AddTerminal addTerminalFrame = new AddTerminal(terminalBean);
        addTerminalFrame.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        TerminalUIHelper.lstTerminals = terminalDAO.getAllTerminals(TerminalPanel.txtSearch.getText());
        terminalservices.generateTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        TerminalUIHelper.addUpdateFlag = "add";
        AddTerminal addTerminalFrame = new AddTerminal();
        addTerminalFrame.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdd;
    public static javax.swing.JButton btnDelete;
    public static javax.swing.JButton btnPrint;
    public static javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    public static javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JTable tblTerminal;
    public static javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
